export declare const ConstDesignTypographyFontSizeUnit: readonly ["px", "em", "rem"];
export type DesignTypographyFontSizeUnit = (typeof ConstDesignTypographyFontSizeUnit)[number];
export declare const ConstDesignTypographyTextAlignUnit: readonly ["center", "justify", "left", "right"];
export type DesignTypographyTextAlignUnit = (typeof ConstDesignTypographyTextAlignUnit)[number];
export declare const ConstDesignTypographyWeightUnit: readonly [100, 200, 300, 400, 500, 600, 700, 800, 900];
export type DesignTypographyWeightUnit = (typeof ConstDesignTypographyWeightUnit)[number];
export declare const ConstDesignTypographyTransformUnit: readonly ["none", "uppercase", "lowercase", "capitalize"];
export type DesignTypographyTransformUnit = (typeof ConstDesignTypographyTransformUnit)[number];
export declare const ConstDesignTypographyStyleUnit: readonly ["normal", "italic", "oblique"];
export type DesignTypographyStyleUnit = (typeof ConstDesignTypographyStyleUnit)[number];
export declare const ConstDesignTypographyDecorationUnit: readonly ["normal", "underline", "overline", "line-through"];
export type DesignTypographyDecorationUnit = (typeof ConstDesignTypographyDecorationUnit)[number];
export declare const ConstDesignTypographyLineHeightUnit: readonly ["normal", "px", "em", "rem"];
export type DesignTypographyLineHeightUnit = (typeof ConstDesignTypographyLineHeightUnit)[number];
export declare const ConstDesignTypographyLetterSpacingUnit: readonly ["px", "em", "rem"];
export type DesignTypographyLetterSpacingUnit = (typeof ConstDesignTypographyLetterSpacingUnit)[number];
export declare const ConstDesignTypographyWordSpacingUnit: readonly ["px", "em", "rem"];
export type DesignTypographyWordSpacingUnit = (typeof ConstDesignTypographyWordSpacingUnit)[number];
export interface DesignTypographyValue {
    fontFamily: string;
    fontSize: number;
    textAlign: DesignTypographyTextAlignUnit;
    color: string;
    fontSizeUnit: DesignTypographyFontSizeUnit;
    weight: DesignTypographyWeightUnit;
    transform: DesignTypographyTransformUnit;
    style: DesignTypographyStyleUnit;
    decoration: DesignTypographyDecorationUnit;
    lineHeight: number;
    lineHeightUnit: DesignTypographyLineHeightUnit;
    letterSpacing: number;
    letterSpacingUnit: DesignTypographyLetterSpacingUnit;
    wordSpacing: number;
    wordSpacingUnit: DesignTypographyWordSpacingUnit;
}
